### ISSUE TITLE
NotImplementedError: _getTypedStream 1014

### ISSUE THREAD

**Issue by pratiknht** [TeamMsgExtractor/msg-extractor#173]
**Bug Metadata:**
* Version of extract_msg: **0.26.2**
* Python version: Python **2.7.12**
* I used the extract_msg package

**Bug description:**
The error message for a few msg files was as below:
* **Error Type:**   NotImplementedError
* **Error Message:**  : The stream specified is of type 1014. We don't currently understand exactly how this type works. If it is mandatory that you have the contents of this stream, please create an issue labled "NotImplementedError: _getTypedStream 1014".

**Error for command:**

```
extract_msg.Message(msg_file)
```

Unfortunately, I cannot share the msg file due to its confidential contents but it gave the error for very few emails ( including attachments & without attachments).

**Comment by TheElementalOfDestruction** [comment]
I'll soon update the version to 0.27.11 with a patch for this. This type was *supposed* to be implemented, but I goofed and missed it. This is also one of the types where I have been trying to get an example to test against, so if you could enable the logging and post a log of the file parsing when the new version is out, I would be grateful. The log will just tell me information about what happened during parsing so I can tell if I implemented it correctly.

**Comment by pratiknht** [comment]
Thanks for the prompt response. I will see if  I can share any .msg file which throws this error.But the logs contain only the following message:
*** NotImplementedError: The stream specified is of type 1014. We don't currently understand exactly how this type works. If it is mandatory that you have the contents of this stream, please create an issue labled "NotImplementedError: _getTypedStream 1014".

Patch for this issue would be very helpful.



| 
Thanks & Regards,
Pratik Nevase
Engineering Team |
| Heaptrace Technology | Allocate dynamic memory to idea..

Tatvem Vertex
Pune, Maharashtra 411027
Email:pratikn@heaptrace.com
 |
| www.heaptrace.com |   |
| The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future. |


 

    On Friday, January 1, 2021, 01:42:55 PM GMT+5:30, Destiny Peterson <notifications@github.com> wrote:  
 
 


I'll soon update the version to 0.27.11 with a patch for this. This type was supposed to be implemented, but I goofed and missed it. This is also one of the types where I have been trying to get an example to test against, so if you could enable the logging and post a log of the file parsing when the new version is out, I would be grateful. The log will just tell me information about what happened during parsing so I can tell if I implemented it correctly.

**Comment by TheElementalOfDestruction** [comment]
Sorry, I just need a log from the logging module after you update to 0.27.11. I just released it on PyPi so you can download it now. Here is a code example that will output the log from the program to the console:
```python
import logging
import sys
# Let's setup the logger
root = logging.getLogger()
root.setLevel(logging.DEBUG)

handler = logging.StreamHandler(sys.stdout)
handler.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
handler.setFormatter(formatter)
root.addHandler(handler)

# Now that the logger is setup, we can import extract_msg and open a message.
import extract_msg
msg = extract_msg.openMsg(message)
```
This log includes any warnings that the module throws, which is why I would like to see it. There is a chance, although small, that this will not output anything which is fine. This log should not output anything confidential and will allow me to know that my code is working.

**Comment by TheElementalOfDestruction** [comment]
Because I didn't get a full traceback, I made the assumption of where the error was being thrown from. This is an example of why it might be useful to a developer to provide a traceback in it's entirety 😛 

Apparently I put that in multiple places and forgot at least one of them, I have to go back and try to find them all. I'll let you know when I have done that.

**Comment by TheElementalOfDestruction** [comment]
I *think* I've fixed it now. Please try the code I provided and let me know.

**Comment by pratiknht** [comment]
Still facing the issue.
Plz refer to the logs

![image](https://user-images.githubusercontent.com/76780971/104303131-b37a8480-54ef-11eb-877f-4e52f23bedce.png)

**Comment by TheElementalOfDestruction** [comment]
Try running the following code for one (or more) of the files that are having problems. This should show me what is going wrong in the code. This specific code will add more information to the log as well as output it directly to the console. If you already have some code to output to a log file, you can comment out the specified lines. Please provide the full log that this produces:
```python
import extract_msg
import extract_msg.utils
from extract_msg import constants

import logging
import sys

root = logging.getLogger()
root.setLevel(logging.DEBUG)

# ADD CONSOLE LOG HANDLER
handler = logging.StreamHandler(sys.stdout)
handler.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
handler.setFormatter(formatter)
root.addHandler(handler)
# END SECTION

class Message(extract_msg.Message):
    def _getTypedStream(self, filename, prefix = True, _type = None):
        """
        Override function. This should work.
        """
        extract_msg.utils.verifyType(_type)
        filename = self.fix_path(filename, prefix)
        for x in (filename + _type,) if _type is not None else self.slistDir():
            if x.startswith(filename) and x.find('-') == -1:
                contents = self._getStream(x, False)
                if len(contents) == 0:
                    return True, None # We found the file, but it was empty.
                extras = []
                _type = x[-4:]
                if x[-4] == '1': # It's a multiple
                    if _type in ('101F', '101E'):
                        streams = len(contents) // 4 # These lengths are normal.
                    elif _type == '1102':
                        streams = len(contents) // 8 # These lengths have 4 0x00 bytes at the end for seemingly no reason. They are "reserved" bytes
                    elif _type in ('1002', '1003', '1004', '1005', '1007', '1014', '1040', '1048'):
                        try:
                            streams = self.mainProperties[x[-8:]].realLength
                        except:
                            root.error('Could not find matching VariableLengthProp for stream {}'.format(x))
                            streams = len(contents) // (2 if _type in constants.MULTIPLE_2_BYTES else 4 if _type in constants.MULTIPLE_4_BYTES else 8 if _type in constants.MULTIPLE_8_BYTES else 16)
                    else:
                        raise NotImplementedError('The stream specified is of type {}. We don\'t currently understand exactly how this type works. If it is mandatory that you have the contents of this stream, please create an issue labled "NotImplementedError: _getTypedStream {}".'.format(_type, _type))
                    if _type in ('101F', '101E', '1102'):
                        if self.Exists(x + '-00000000', False):
                            for y in range(streams):
                                if self.Exists(x + '-' + extract_msg.utils.properHex(y, 8), False):
                                    extras.append(self._getStream(x + '-' + extract_msg.utils.properHex(y, 8), False))
                    elif _type in ('1002', '1003', '1004', '1005', '1007', '1014', '1040', '1048'):
                        extras = extract_msg.utils.divide(contents, (2 if _type in constants.MULTIPLE_2_BYTES else 4 if _type in constants.MULTIPLE_4_BYTES else 8 if _type in constants.MULTIPLE_8_BYTES else 16))
                        contents = streams
                if _type == '1014':
                    root.debug(contents)
                    root.debug(extras)
                try:
                    return True, extract_msg.utils.parseType(int(_type, 16), contents, self.stringEncoding, extras)
                except Exception as e:
                    root.exception(e)
                    raise
        return False, None # We didn't find the stream.

msg = Message(MESSAGE_PATH)
```

**Comment by kvalo** [comment]
I have the same problem and unfortunately I'm not able share an example mail file either. I ran the test code above, but without printing contents or extras variables as I don't know what information they contain. The output I got:

2021-03-02 17:29:22,220 - root - DEBUG - Found type of 1014
2021-03-02 17:29:22,220 - extract_msg.utils - WARNING - Error while parsing multiple type. Expected 40 entries, got 5. Ignoring.
2021-03-02 17:29:22,223 - root - DEBUG - Found type of 1014
2021-03-02 17:29:22,223 - extract_msg.utils - WARNING - Error while parsing multiple type. Expected 40 entries, got 5. Ignoring.
2021-03-02 17:29:22,227 - root - DEBUG - Found type of 1014
2021-03-02 17:29:22,227 - extract_msg.utils - WARNING - Error while parsing multiple type. Expected 120 entries, got 15. Ignoring.

Any ideas what I should test next?

I'm using extract-msg (0.28.6) installed with pip3 and python 3.5.2 on Ubuntu 16.04.

**Comment by TheElementalOfDestruction** [comment]
@kvalo Can you please run the code in the message above yours and post the results here? Thank you.

**Comment by kvalo** [comment]
I did, expect that I commented out these two lines:

#root.debug(contents)
#root.debug(extras)

What do these variables actually contain?

**Comment by TheElementalOfDestruction** [comment]
@kvalo Those variables contain that data that is being parsed. This specific type of data is of type 0x1014 (PtypMultipleInteger64) and so would just be random numbers without anything to identify what they could mean in the context of the email. By looking at these streams, I'll be able to see what the structure looks like and figure out why the code is reading them incorrectly (technically it looks like they are read correctly, the length is just being incorrectly calculated). Please run the code exactly as I put it (I added another line to give me a bit more information, so copy the code again from the message, please). Thank you for your time.

**Comment by kvalo** [comment]
Unfortunately I cannot print any information from the email itself so I removed the debug prints for contents and extras again, I hope you understand. The new output is below. But I can try to debug this myself further, so if you have any ideas or pointers what I should investigate first do let me know.

2021-03-02 18:00:28,077 - root - DEBUG - Real length: 5
2021-03-02 18:00:28,090 - root - DEBUG - Real length: 40
2021-03-02 18:00:28,090 - root - DEBUG - Found type of 1014
2021-03-02 18:00:28,090 - extract_msg.utils - WARNING - Error while parsing multiple type. Expected 40 entries, got 5. Ignoring.
2021-03-02 18:00:28,093 - root - DEBUG - Real length: 40
2021-03-02 18:00:28,093 - root - DEBUG - Found type of 1014
2021-03-02 18:00:28,093 - extract_msg.utils - WARNING - Error while parsing multiple type. Expected 40 entries, got 5. Ignoring.
2021-03-02 18:00:28,097 - root - DEBUG - Real length: 120
2021-03-02 18:00:28,097 - root - DEBUG - Found type of 1014
2021-03-02 18:00:28,097 - extract_msg.utils - WARNING - Error while parsing multiple type. Expected 120 entries, got 15. Ignoring.

**Comment by TheElementalOfDestruction** [comment]
Well it looks like the way it calculates length is different in the property than in that specific function, so I can try to look at that. The main thing I am looking for is where the `\x00`s are in the data. Do they appear before it, after it, etc.?

**Comment by TheElementalOfDestruction** [comment]
Ohhhh, I see that 0x1014 actually has no length specified at all. There's your problem.

**Comment by TheElementalOfDestruction** [comment]
@kvalo Could you run the code again and tell me if you still get those warnings?

**Comment by kvalo** [comment]
I upgraded to v0.28.7, only had time for a quick test but these stream 1014 problems seem to be solved now. I can do more extensive testing tomorrow. Thank you so much!

**Comment by kvalo** [comment]
I tested v0.28.7 more today and didn't spot any issues, so my point of view this issue is fixed now. Thank you again!
