### ISSUE TITLE
Message and attachment class save method issue

### ISSUE THREAD

**Issue by DChaitanya** [TeamMsgExtractor/msg-extractor#184]
For some of msg sample file, we get embedded null byte error while calling save method.

The dirName, filename contains hex chars '\x00' at the end, due to this while creating directory or file getting following errors - 

Traceback (most recent call last):
  File "msg_extractor.py", line 278, in <module>
    print(msg_extract(cf))
  File "msg_extractor.py", line 265, in msg_extract
    extracted_file_details, dir_name = msg.save(useFileName=True, customPath=base_path)
  File "msg_extractor.py", line 169, in save
    attachmentNames.append(attachment.save(ContentId, toJson, useFileName, raw, html = html, rtf = rtf))
  File "/usr/local/lib/python3.8/site-packages/extract_msg/attachment.py", line 80, in save
    with open(filename, 'wb') as f:
ValueError: embedded null byte

To solve this issue, I created work around, but it better if you add it in main source - 

>     if isinstance(filename, bytes):
>         filename = filename.decode("utf-8", "replace").rstrip('\x00')
>     else:
>         filename = filename.rstrip('\x00')

**Comment by TheElementalOfDestruction** [comment]
That's a weird thing that happened. As far as I am aware, there should *never* be a null character in the filename. I'll add some code that does this properly (as we can't use use a singular encoding and should actually refer back to the encoding of the file) to try and make sure there is never a null character there.

**Comment by TheElementalOfDestruction** [comment]
This should be fixed now. Let me know if you have any more issues.

**Comment by DChaitanya** [comment]
Error is still exist. Can you please check pseudo code below -

```
import extract_msg
m = extract_msg.Message("sample.msg", overrideEncoding="utf-8")
m.save()
```

Sample msg message  - 
[sample.zip](https://github.com/TeamMsgExtractor/msg-extractor/files/6001818/sample.zip)

**Comment by TheElementalOfDestruction** [comment]
Ah, it arose in a different spot this time. This email in general just seems to be bad (missing an encoding, properties randomly ending with a null character) so it's no wonder there are so many issues. I'll see what I can do.

**Comment by TheElementalOfDestruction** [comment]
I think I fixed it in the newest update, but I hate to ask: did Outlook generate these files?

**Comment by DChaitanya** [comment]
Yes, this is generated from outlook. Is there any way to detect the encoding encoding missing in file headers.

**Comment by TheElementalOfDestruction** [comment]
Unfortunately msg files have exactly 2 properties (that I have found) that relate to encoding. The first is a Boolean that says if it is encoded in Unicode (specifically UTF-16-LE IIRC) and the second tells what encoding it is if it is not encoded that way. Unfortunately, the second property is marked as something that *should* exist rather than *must* and without it the best you can do is guess the encoding and pray that it is correct. And that property is sometimes not even correct, from the information I have gathered.

**Comment by TheElementalOfDestruction** [comment]
This issue appears to be solved, so I am closing it. If you disagree with this please let me know.
