### ISSUE TITLE
AttributeError: module 'RTFDE' has no attribute 'NotEncapsulatedRtf'

### ISSUE THREAD

**Issue by marcboivin** [TeamMsgExtractor/msg-extractor#249]
In order to get your bug addressed in a timely manner, or at all :smiley:, please fill out the below bug report. Please try to make it as easy as possible for us to understand what is going on. We may close out any bugs or issues without warning that are not complete or coherent.

In the bug template below anything is [square brackets] should be filled out or removed if the item doesn't apply.

Should you encounter an error that has not already been reported, please do the following when reporting it:
**Bug Metadata**
* Version of extract_msg: [0.30.9]
* Your python version: Python [ 3.9.9]
* How did you launch extract_msg?
  - [x ] My command line or
  - [x ] I used the extract_msg package

**Describe the bug**
Extracting a message return the error: AttributeError: module 'RTFDE' has no attribute 'NotEncapsulatedRtf'

[ If applicable ]
**What code did you use or can we use to reproduce this error?

```
[put your code here]
```

Is there a message.msg file you want to share to help us reproduce this? I can't as it can contain very sensible information.
- [ ] Uploaded message (drag and drop on this window)
- [ ] Emailed message as an attachment to admins: [Enter Subject Line Here]

**Traceback**
```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/lark/lexer.py", line 486, in lex
    token = self.root_lexer.next_token(lexer_state, parser_state)
  File "/opt/homebrew/lib/python3.9/site-packages/lark/lexer.py", line 398, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: No terminal matches '\' in the current parser context, at line 47 col 112

0 <p class="MsoNormal"><o:p>}\pard\plain\~{\*\htmltag0 </o:p></P>}{\*\htmltag0 }
                                        ^
Expected one of:
	* CONTROLWORD
	* CONTROLSYMBOL
	* TEXT
	* RTFESCAPE
	* OPENPAREN
	* CLOSEPAREN

Previous tokens: Token('CONTROLWORD', '\\plain')


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/message_base.py", line 293, in deencapsulatedRtf
    self._deencapsultor.deencapsulate()
  File "/opt/homebrew/lib/python3.9/site-packages/RTFDE/deencapsulate.py", line 130, in deencapsulate
    self.doc_tree = self._parse_rtf()
  File "/opt/homebrew/lib/python3.9/site-packages/RTFDE/deencapsulate.py", line 164, in _parse_rtf
    self.full_tree = parser.parse(self.simplified_rtf)
  File "/opt/homebrew/lib/python3.9/site-packages/lark/lark.py", line 581, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/opt/homebrew/lib/python3.9/site-packages/lark/parser_frontends.py", line 106, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/opt/homebrew/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 41, in parse
    return self.parser.parse(lexer, start)
  File "/opt/homebrew/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 171, in parse
    return self.parse_from_state(parser_state)
  File "/opt/homebrew/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 188, in parse_from_state
    raise e
  File "/opt/homebrew/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 178, in parse_from_state
    for token in state.lexer.lex(state):
  File "/opt/homebrew/lib/python3.9/site-packages/lark/lexer.py", line 489, in lex
    raise e  # Raise the original UnexpectedCharacters. The root lexer raises it with the wrong expected set.
  File "/opt/homebrew/lib/python3.9/site-packages/lark/lexer.py", line 478, in lex
    yield lexer.next_token(lexer_state, parser_state)
  File "/opt/homebrew/lib/python3.9/site-packages/lark/lexer.py", line 398, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: No terminal matches '\' in the current parser context, at line 47 col 112

0 <p class="MsoNormal"><o:p>}\pard\plain\~{\*\htmltag0 </o:p></P>}{\*\htmltag0 }
                                        ^
Expected one of:
	* CONTROLWORD
	* CONTROLSYMBOL
	* TEXT
	* RTFESCAPE
	* OPENPAREN
	* CLOSEPAREN

Previous tokens: Token('CONTROLWORD', '\\plain')


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mboivin/Documents/dev/egr-mail-info/./run.py", line 85, in <module>
    main()
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/mboivin/Documents/dev/egr-mail-info/./run.py", line 32, in main
    msg = extract_msg.Message(msg_file)
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/message.py", line 26, in __init__
    super().__init__(path, prefix, attachmentClass, filename, delayAttachments, overrideEncoding, attachmentErrorBehavior, recipientSeparator)
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/message_base.py", line 65, in __init__
    self.attachments
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/message_base.py", line 176, in attachments
    self._attachments.append(self.attachmentClass(self, attachmentDir))
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/attachment.py", line 46, in __init__
    self.__data = openMsg(self.msg.path, self.__prefix, self.__class__, overrideEncoding = msg.overrideEncoding, attachmentErrorBehavior = msg.attachmentErrorBehavior, strict = False)
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/utils.py", line 607, in openMsg
    return Message(path, prefix, attachmentClass, filename, delayAttachments, overrideEncoding, attachmentErrorBehavior, recipientSeparator)
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/message.py", line 26, in __init__
    super().__init__(path, prefix, attachmentClass, filename, delayAttachments, overrideEncoding, attachmentErrorBehavior, recipientSeparator)
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/message_base.py", line 71, in __init__
    self.body
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/message_base.py", line 243, in body
    if self.deencapsulatedRtf and self.deencapsulatedRtf.content_type == 'text':
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/message_base.py", line 294, in deencapsulatedRtf
    except RTFDE.NotEncapsulatedRtf as e:
AttributeError: module 'RTFDE' has no attribute 'NotEncapsulatedRtf'
➜  egr-mail-info extract_msg fail2.msg
Error with file "fail2.msg": Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/lark/lexer.py", line 486, in lex
    token = self.root_lexer.next_token(lexer_state, parser_state)
  File "/opt/homebrew/lib/python3.9/site-packages/lark/lexer.py", line 398, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: No terminal matches '\' in the current parser context, at line 47 col 112

0 <p class="MsoNormal"><o:p>}\pard\plain\~{\*\htmltag0 </o:p></P>}{\*\htmltag0 }
                                        ^
Expected one of:
	* RTFESCAPE
	* OPENPAREN
	* TEXT
	* CLOSEPAREN
	* CONTROLSYMBOL
	* CONTROLWORD

Previous tokens: Token('CONTROLWORD', '\\plain')


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/message_base.py", line 293, in deencapsulatedRtf
    self._deencapsultor.deencapsulate()
  File "/opt/homebrew/lib/python3.9/site-packages/RTFDE/deencapsulate.py", line 130, in deencapsulate
    self.doc_tree = self._parse_rtf()
  File "/opt/homebrew/lib/python3.9/site-packages/RTFDE/deencapsulate.py", line 164, in _parse_rtf
    self.full_tree = parser.parse(self.simplified_rtf)
  File "/opt/homebrew/lib/python3.9/site-packages/lark/lark.py", line 581, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/opt/homebrew/lib/python3.9/site-packages/lark/parser_frontends.py", line 106, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/opt/homebrew/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 41, in parse
    return self.parser.parse(lexer, start)
  File "/opt/homebrew/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 171, in parse
    return self.parse_from_state(parser_state)
  File "/opt/homebrew/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 188, in parse_from_state
    raise e
  File "/opt/homebrew/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 178, in parse_from_state
    for token in state.lexer.lex(state):
  File "/opt/homebrew/lib/python3.9/site-packages/lark/lexer.py", line 489, in lex
    raise e  # Raise the original UnexpectedCharacters. The root lexer raises it with the wrong expected set.
  File "/opt/homebrew/lib/python3.9/site-packages/lark/lexer.py", line 478, in lex
    yield lexer.next_token(lexer_state, parser_state)
  File "/opt/homebrew/lib/python3.9/site-packages/lark/lexer.py", line 398, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: No terminal matches '\' in the current parser context, at line 47 col 112

0 <p class="MsoNormal"><o:p>}\pard\plain\~{\*\htmltag0 </o:p></P>}{\*\htmltag0 }
                                        ^
Expected one of:
	* RTFESCAPE
	* OPENPAREN
	* TEXT
	* CLOSEPAREN
	* CONTROLSYMBOL
	* CONTROLWORD

Previous tokens: Token('CONTROLWORD', '\\plain')


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/__main__.py", line 68, in main
    with utils.openMsg(x[0]) as msg:
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/utils.py", line 607, in openMsg
    return Message(path, prefix, attachmentClass, filename, delayAttachments, overrideEncoding, attachmentErrorBehavior, recipientSeparator)
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/message.py", line 26, in __init__
    super().__init__(path, prefix, attachmentClass, filename, delayAttachments, overrideEncoding, attachmentErrorBehavior, recipientSeparator)
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/message_base.py", line 65, in __init__
    self.attachments
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/message_base.py", line 176, in attachments
    self._attachments.append(self.attachmentClass(self, attachmentDir))
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/attachment.py", line 46, in __init__
    self.__data = openMsg(self.msg.path, self.__prefix, self.__class__, overrideEncoding = msg.overrideEncoding, attachmentErrorBehavior = msg.attachmentErrorBehavior, strict = False)
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/utils.py", line 607, in openMsg
    return Message(path, prefix, attachmentClass, filename, delayAttachments, overrideEncoding, attachmentErrorBehavior, recipientSeparator)
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/message.py", line 26, in __init__
    super().__init__(path, prefix, attachmentClass, filename, delayAttachments, overrideEncoding, attachmentErrorBehavior, recipientSeparator)
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/message_base.py", line 71, in __init__
    self.body
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/message_base.py", line 243, in body
    if self.deencapsulatedRtf and self.deencapsulatedRtf.content_type == 'text':
  File "/opt/homebrew/lib/python3.9/site-packages/extract_msg/message_base.py", line 294, in deencapsulatedRtf
    except RTFDE.NotEncapsulatedRtf as e:
AttributeError: module 'RTFDE' has no attribute 'NotEncapsulatedRtf'
```

**Screenshots**
[Insert any screenshots or debug pictures here]

**Additional context**
[Add any other context about the problem here.]

**Comment by TheElementalOfDestruction** [comment]
I'm slowly finding out my current set of test files is missing a lot of cases. Thanks, this will be fixed (along with another issue in the same function) in just a few minutes

**Comment by TheElementalOfDestruction** [comment]
Alright, I just published v0.30.10 and this should now be fixed. Let me know if you have any other problems.

**Comment by marcboivin** [comment]
Testing right now

**Comment by marcboivin** [comment]
Ok so problem still there. I'm trying to give you an msg file that replicates the issue without the highly sensitive data in it. Stay tuned.

**Comment by marcboivin** [comment]
Here is the offending Encapsulated RTF. Did my best to remove all sensitive information. 
```

b'{\\rtf1\\ansi\\fbidis\\ansicpg1252\\deff0\\fromhtml1{\\fonttbl{\\f0\\fswiss\\fcharset0 Times New Roman;}{\\f1\\fswiss\\fcharset2 Symbol;}{\\f2\r\n\\fswiss\\fcharset0 Calibri;}{\\f3\\fswiss\\fcharset0 Verdana;}}\r\n{\\colortbl;\\red192\\green192\\blue192;\\red255\\green255\\blue255;\\red0\\green0\\blue1;\\red43\\green59\\blue70;\\red0\\green0\\blue255\r\n;\\red5\\green99\\blue193;\\red167\\green207\\blue56;\\red42\\green59\\blue69;\\red60\\green60\\blue59;}\r\n{\\*\\generator Microsoft Exchange Server;}\r\n{\\*\\formatConverter converted from html;}\r\n\\viewkind5\\viewscale100\r\n\\htmlrtf{\\*\\bkmkstart BM_BEGIN}\\htmlrtf0{\\*\\htmltag64}{\\*\\htmltag0 <html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta name="Generator" content="Microsoft Word 15 (filtered medium)"><!--[if !mso]><style>v\\\\:* \\{behavior:url(#default#VML);\\}\\par\r\no\\\\:* \\{behavior:url(#default#VML);\\}\\par\r\nw\\\\:* \\{behavior:url(#default#VML);\\}\\par\r\n.shape \\{behavior:url(#default#VML);\\}\\par\r\n</style><![endif]--><style><!--\\par\r\n/* Font Definitions */\\par\r\n@font-face\\par\r\n\\\'09\\{font-family:"Cambria Math";\\par\r\n\\\'09panose-1:2 4 5 3 5 4 6 3 2 4;\\}\\par\r\n@font-face\\par\r\n\\\'09\\{font-family:Calibri;\\par\r\n\\\'09panose-1:2 15 5 2 2 2 4 3 2 4;\\}\\par\r\n@font-face\\par\r\n\\\'09\\{font-family:Verdana;\\par\r\n\\\'09panose-1:2 11 6 4 3 5 4 4 2 4;\\}\\par\r\n/* Style Definitions */\\par\r\np.MsoNormal, li.MsoNormal, div.MsoNormal\\par\r\n\\\'09\\{margin:0cm;\\par\r\n\\\'09font-size:11.0pt;\\par\r\n\\\'09font-family:"Calibri",sans-serif;\\par\r\n\\\'09mso-fareast-language:EN-US;\\}\\par\r\nspan.EmailStyle17\\par\r\n\\\'09\\{mso-style-type:personal-compose;\\par\r\n\\\'09font-family:"Calibri",sans-serif;\\par\r\n\\\'09color:windowtext;\\}\\par\r\n.MsoChpDefault\\par\r\n\\\'09\\{mso-style-type:export-only;\\par\r\n\\\'09font-family:"Calibri",sans-serif;\\par\r\n\\\'09mso-fareast-language:EN-US;\\}\\par\r\n@page WordSection1\\par\r\n\\\'09\\{size:612.0pt 792.0pt;\\par\r\n\\\'09margin:72.0pt 72.0pt 72.0pt 72.0pt;\\}\\par\r\ndiv.WordSection1\\par\r\n\\\'09\\{page:WordSection1;\\}\\par\r\n--></Style><!--[if gte mso 9]><xml>\\par\r\n<o:shapedefaults v:ext="edit" spidmax="1026" />\\par\r\n</xml><![endif]--><!--[if gte mso 9]><xml>\\par\r\n<o:shapelayout v:ext="edit">\\par\r\n<o:idmap v:ext="edit" data="1" />\\par\r\n</o:shapelayout></xml><![endif]--></Head><body lang="EN-GB" link="#0563C1" vlink="#954F72" style="word-wrap:break-word"><div class="WordSection1">}{\\*\\htmltag0 <p class="MsoNormal">}\\pard\r\n\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0 Hi {\\*\\htmltag0 <o:p></o:p></P>}\\htmlrtf}\\htmlrtf0{\\*\\htmltag0 }\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal"><o:p>}\\pard\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0\\~{\\*\\htmltag0 </o:p></P>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 }\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal">}\\pard\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0 We have a sstomer has staite or they may consider seeking refund (\\\'A30k) plus other additional costs they deem suitable.{\\*\\htmltag0 <o:p></o:p></P>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 }\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal"><o:p>}\\pard\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0\\~{\\*\\htmltag0 </o:p></P>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 }\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal">}\\pard\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0 We did respllow up latter. I have attached all 3 commuur reference.{\\*\\htmltag0 <br>}\\htmlrtf\r\n}{\\f2\\lang2057\\fs22\\line\r\n\\htmlrtf0{\\*\\htmltag0\\par}{\\*\\htmltag0 <br>}\\htmlrtf}{\\f2\\lang2057\\fs22\\line\r\n\\htmlrtf0{\\*\\htmltag0\\par}We have startedmost places.{\\*\\htmltag0 <o:p></o:p></P>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 }\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal"><o:p>}\\pard\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0\\~{\\*\\htmltag0 </o:p></P>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 }\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal">}\\pard\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0 A brier quality data.{\\*\\htmltag0 <o:p></o:p></P>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 }\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal"><o:p>}\\pard\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0\\~{\\*\\htmltag0 </o:p></P>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 }\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal">}\\pard\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0 We do not we know about the poeve the 1{\\*\\htmltag0 <sup>}\\htmlrtf\r\n}{\\f2\\lang2057\\super\\htmlrtf0 st{\\*\\htmltag0 </Sup>}\\htmlrtf}{\\f2\\lang2057\\fs22\\htmlrtf0  Marset for us.{\\*\\htmltag0 <o:p></o:p></P>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 }\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal"><o:p>}\\pard\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0\\~{\\*\\htmltag0 </o:p></P>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 }\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal">}\\pard\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0 I hoiew later today?{\\*\\htmltag0 <o:p></o:p></P>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 }\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal"><o:p>}\\pard\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0\\~{\\*\\htmltag0 </o:p></P>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 }\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal">}\\pard\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0 Thanks{\\*\\htmltag0 <o:p></o:p></P>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 }\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal"><o:p>}\\pard\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0\\~{\\*\\htmltag0 </o:p></P>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 }\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal">}\\pard\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0 {\\*\\htmltag0 <o:p></o:p></P>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 }\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal"><o:p>}\\pard\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0\\~{\\*\\htmltag0 </o:p></P>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 }\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal"><o:p>}\\pard\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0\\~{\\*\\htmltag0 </o:p></P>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 }\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal"><o:p>}\\pard\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0\\~{\\*\\htmltag0 </o:p></P>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 }\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal"><span style="mso-fareast-language:EN-GB">}{\\*\\htmltag0 <o:p>}\\pard\\plain\\htmlrtf{\\f2\\lang2057\r\n\\fs22\\htmlrtf0\\~{\\*\\htmltag0 </o:p></Span>}\\htmlrtf}\\htmlrtf0{\\*\\htmltag0 </P>}\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <table class="MsoNormalTable" border="0" cellspacing="0" cellpadding="0" align="left" width="600" style="width:450.0pt;background:white;border-collapse:collapse"><tbody>}{\\*\\htmltag0 <tr><td valign="top" style="padding:0cm 0cm 0cm 0cm">}{\\*\\htmltag0 <table class="MsoNormalTable" border="0" cellspacing="0" cellpadding="0">}\\htmlrtf\r\n\\trowd\\irow0\\irowband0\\trcbpat2\\clpadl0\\clpadfl3\\clpadr0\\clpadfr3\\clpadb0\\clpadfb3\\clpadt0\\clpadft3\\clcbpat2\\cellx8856\\htmlrtf0\r\n{\\*\\htmltag0 <tbody>}{\\*\\htmltag0 <tr style="height:15.6pt"><td style="padding:0cm 0cm 0cm 0cm;height:15.6pt">}{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly">}{\\*\\htmltag0 <span style="font-size:9.0pt;color:#000001;mso-fareast-language:EN-GB">}{\\*\\htmltag0 <img width="1" height="26" style="width:.0138in;height:.2708in" id="Picture_x0020_7" src="cid:image001.gif@01D82331.3F8C7950"></Span>}\\pard\r\n\\intbl\\itap2\\cbpat2\\plain{\\*\\htmltag0 }\\htmlrtf\\objattph  \\htmlrtf0{\\*\\htmltag0 <span style="font-size:9.0pt;color:#000001;mso-fareast-language:EN-GB"><o:p></o:p></Span></P>}\\htmlrtf\r\n\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly"><span style="font-size:9.0pt;color:#000001;mso-fareast-language:EN-GB">}{\\*\\htmltag0 <o:p>}\\pard\r\n\\intbl\\itap2\\cbpat2\\plain\\htmlrtf{\\f2\\lang2057\\cf3\\fs18\\htmlrtf0\\~{\\*\\htmltag0 </o:p></Span>}\\htmlrtf}\\htmlrtf0{\\*\\htmltag0 </P>}\\htmlrtf\r\n\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly"><span style="font-size:9.0pt;font-family:"Verdana",sans-serif;color:#000001;mso-fareast-language:EN-GB">}\\pard\r\n\\intbl\\itap2\\cbpat2\\plain\\htmlrtf{\\f3\\lang2057\\cf3\\fs18\\htmlrtf0 Kind Regards{\\*\\htmltag0 </Span>}\\htmlrtf}\\htmlrtf0{\\*\\htmltag0 <span style="font-size:10.0pt;font-family:"Verdana",sans-serif;color:#000001;mso-fareast-language:EN-GB"><o:p></o:p></Span></P>}\\htmlrtf\r\n\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly"><span style="font-size:10.0pt;color:#000001;mso-fareast-language:EN-GB">}{\\*\\htmltag0 <o:p>}\\pard\r\n\\intbl\\itap2\\cbpat2\\plain\\htmlrtf{\\f2\\lang2057\\cf3\\fs20\\htmlrtf0\\~{\\*\\htmltag0 </o:p></Span>}\\htmlrtf}\\htmlrtf0{\\*\\htmltag0 </P>}{\\*\\htmltag0 </TD>}\\htmlrtf\r\n\\nestcell{\\nonesttables\\tab}\\htmlrtf0{\\*\\htmltag0 </TR>}\\htmlrtf\\pard\\intbl\\itap2{\\*\\nesttableprops\\trowd\\irow0\\irowband0\\trcbpat2\r\n\\trrh312\\clpadl0\\clpadfl3\\clpadr0\\clpadfr3\\clpadb0\\clpadfb3\\clpadt0\\clpadft3\\clcbpat2\\cellx8856\\nestrow}{\\nonesttables\\par}\r\n\\htmlrtf0{\\*\\htmltag0 <tr><td style="padding:0cm 0cm 0cm 0cm">}{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly">}{\\*\\htmltag0 <b>}{\\*\\htmltag0 <span style="font-size:9.0pt;font-family:"Verdana",sans-serif;color:#2B3B46;letter-spacing:-.15pt;mso-fareast-language:EN-GB">}\\pard\r\n\\intbl\\itap2\\cbpat2\\plain\\htmlrtf{\\f3\\lang2057\\cf4\\fs18\\b\\htmlrtf0 C{\\*\\htmltag0 </Span>}\\htmlrtf}\\htmlrtf0{\\*\\htmltag0 </B><span style="font-size:9.0pt;font-family:"Verdana",sans-serif;color:#000001;mso-fareast-language:EN-GB"><o:p></o:p></Span></P>}{\\*\\htmltag0 </TD>}\\htmlrtf\r\n\\nestcell{\\nonesttables\\tab}\\htmlrtf0{\\*\\htmltag0 </TR>}\\htmlrtf\\pard\\intbl\\itap2{\\*\\nesttableprops\\trowd\\irow1\\irowband1\\trcbpat2\r\n\\clpadl0\\clpadfl3\\clpadr0\\clpadfr3\\clpadb0\\clpadfb3\\clpadt0\\clpadft3\\clcbpat2\\cellx8856\\nestrow}{\\nonesttables\\par}\r\n\\htmlrtf0{\\*\\htmltag0 <tr><td style="padding:0cm 0cm 0cm 0cm">}{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly">}{\\*\\htmltag0 <span style="font-size:9.0pt;font-family:"Verdana",sans-serif;color:#2B3B46;letter-spacing:-.15pt;mso-fareast-language:EN-GB">}\\pard\r\n\\intbl\\itap2\\cbpat2\\plain\\htmlrtf{\\f3\\lang2057\\cf4\\fs18\\htmlrtf0 Viles &amp; Support {\\*\\htmltag0 </Span>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 <span style="font-size:9.0pt;font-family:"Verdana",sans-serif;color:#000001;mso-fareast-language:EN-GB"><o:p></o:p></Span></P>}{\\*\\htmltag0 </TD>}\\htmlrtf\r\n\\nestcell{\\nonesttables\\tab}\\htmlrtf0{\\*\\htmltag0 </TR>}\\htmlrtf\\pard\\intbl\\itap2{\\*\\nesttableprops\\trowd\\irow2\\irowband2\\trcbpat2\r\n\\clpadl0\\clpadfl3\\clpadr0\\clpadfr3\\clpadb0\\clpadfb3\\clpadt0\\clpadft3\\clcbpat2\\cellx8856\\nestrow}{\\nonesttables\\par}\r\n\\htmlrtf0{\\*\\htmltag0 <tr style="height:6.0pt"><td style="padding:0cm 0cm 0cm 0cm;height:6.0pt">}{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly">}{\\*\\htmltag0 <span style="font-size:9.0pt;font-family:"Verdana",sans-serif;color:#000001;mso-fareast-language:EN-GB">}{\\*\\htmltag0 <img width="1" height="10" style="width:.0138in;height:.1041in" id="Picture_x0020_8" src="cid:image001.gif@01D82331.3F8C7950"><o:p></o:p></Span>}\\pard\r\n\\intbl\\itap2\\cbpat2\\plain{\\*\\htmltag0 }\\htmlrtf\\objattph  \\htmlrtf0{\\*\\htmltag0 </P>}{\\*\\htmltag0 </TD>}\\htmlrtf\\nestcell{\\nonesttables\\tab}\\htmlrtf0\r\n{\\*\\htmltag0 </TR>}\\htmlrtf\\pard\\intbl\\itap2{\\*\\nesttableprops\\trowd\\irow3\\irowband3\\trcbpat2\\trrh120\\clpadl0\\clpadfl3\\clpadr0\r\n\\clpadfr3\\clpadb0\\clpadfb3\\clpadt0\\clpadft3\\clcbpat2\\cellx8856\\nestrow}{\\nonesttables\\par}\r\n\\htmlrtf0{\\*\\htmltag0 <tr><td style="padding:0cm 0cm 0cm 0cm">}{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly">}{\\*\\htmltag0 <span style="font-size:9.0pt;font-family:"Verdana",sans-serif;color:#000001;mso-fareast-language:EN-GB">}\\pard\r\n\\intbl\\itap2\\cbpat2\\plain\\htmlrtf{\\f3\\lang2057\\cf3\\fs18\\htmlrtf0 +44 (0)7788 365 955{\\*\\htmltag0 <o:p></o:p></Span>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 </P>}{\\*\\htmltag0 </TD>}\\htmlrtf\\nestcell{\\nonesttables\\tab}\\htmlrtf0{\\*\\htmltag0 </TR>}\\htmlrtf\\pard\\intbl\r\n\\itap2{\\*\\nesttableprops\\trowd\\irow4\\irowband4\\trcbpat2\\clpadl0\\clpadfl3\\clpadr0\\clpadfr3\\clpadb0\\clpadfb3\\clpadt0\\clpadft3\r\n\\clcbpat2\\cellx8856\\nestrow}{\\nonesttables\\par}\r\n\\htmlrtf0{\\*\\htmltag0 <tr><td style="padding:0cm 0cm 0cm 0cm">}{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly">}{\\*\\htmltag0 <span style="font-size:9.0pt;font-family:"Verdana",sans-serif;mso-fareast-language:EN-GB">}{\\*\\htmltag0 <a href="mailto:cemery@senceive.com"><span style="color:#0563C1">}\\pard\r\n\\intbl\\itap2\\cbpat2\\plain\\htmlrtf{\\field{\\*\\fldinst HYPERLINK "mailto:ceme@e.com" }{\\fldrslt{\\f3\\lang2057\\cf6\\fs18\r\n\\ul\\htmlrtf0 cemery@senceive.com{\\*\\htmltag0 </Span>}\\htmlrtf}\\htmlrtf0{\\*\\htmltag0 </A>}\\htmlrtf}}\\htmlrtf0{\\*\\htmltag0 <o:p></o:p></Span></P>}{\\*\\htmltag0 </TD>}\\htmlrtf\r\n\\nestcell{\\nonesttables\\tab}\\htmlrtf0{\\*\\htmltag0 </TR>}\\htmlrtf\\pard\\intbl\\itap2{\\*\\nesttableprops\\trowd\\irow5\\irowband5\\trcbpat2\r\n\\clpadl0\\clpadfl3\\clpadr0\\clpadfr3\\clpadb0\\clpadfb3\\clpadt0\\clpadft3\\clcbpat2\\cellx8856\\nestrow}{\\nonesttables\\par}\r\n\\htmlrtf0{\\*\\htmltag0 <tr><td style="padding:0cm 0cm 0cm 0cm">}{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly">}{\\*\\htmltag0 <span style="font-size:9.0pt;font-family:"Verdana",sans-serif;color:#2B3B46;letter-spacing:-.15pt;mso-fareast-language:EN-GB">}{\\*\\htmltag0 <a href="https://www.linkedin.com/" target="_blank"><b>}\\pard\r\n\\intbl\\itap2\\cbpat2\\plain{\\*\\htmltag0 <span style="color:#A7CF38">}\\htmlrtf{\\field{\\*\\fldinst HYPERLINK "https://www.linkedin.com/in//" }{\\fldrslt\r\n{\\f3\\lang2057\\cf7\\fs18\\b\\ul\\htmlrtf0 Connect\\~{\\*\\htmltag0 </Span>}\\htmlrtf}\\htmlrtf0{\\*\\htmltag0 </B></A>}\\htmlrtf}}{\\f3\\lang2057\r\n\\cf4\\fs18\\htmlrtf0 with me on LinkedIn{\\*\\htmltag0 </Span>}\\htmlrtf}\\htmlrtf0{\\*\\htmltag0 <span style="font-size:9.0pt;font-family:"Verdana",sans-serif;color:#000001;mso-fareast-language:EN-GB"><o:p></o:p></Span></P>}{\\*\\htmltag0 </TD>}\\htmlrtf\r\n\\nestcell{\\nonesttables\\tab}\\htmlrtf0{\\*\\htmltag0 </TR>}\\htmlrtf\\pard\\intbl\\itap2{\\*\\nesttableprops\\trowd\\irow6\\irowband6\\trcbpat2\r\n\\clpadl0\\clpadfl3\\clpadr0\\clpadfr3\\clpadb0\\clpadfb3\\clpadt0\\clpadft3\\clcbpat2\\cellx8856\\nestrow}{\\nonesttables\\par}\r\n\\htmlrtf0{\\*\\htmltag0 <tr style="height:8.4pt"><td style="padding:0cm 0cm 0cm 0cm;height:8.4pt">}{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly">}{\\*\\htmltag0 <span style="font-size:10.0pt;color:#000001;mso-fareast-language:EN-GB">}{\\*\\htmltag0 <img border="0" width="1" height="14" style="width:.0138in;height:.1458in" id="Picture_x0020_3" src="cid:image001.gif@01D82331.3F8C7950"></Span>}\\pard\r\n\\intbl\\itap2\\cbpat2\\plain{\\*\\htmltag0 }\\htmlrtf\\objattph  \\htmlrtf0{\\*\\htmltag0 <span style="font-size:10.0pt;color:#000001;mso-fareast-language:EN-GB"><o:p></o:p></Span></P>}{\\*\\htmltag0 </TD>}\\htmlrtf\r\n\\nestcell{\\nonesttables\\tab}\\htmlrtf0{\\*\\htmltag0 </TR>}\\htmlrtf\\pard\\intbl\\itap2{\\*\\nesttableprops\\trowd\\irow7\\irowband7\\trcbpat2\r\n\\trrh168\\clpadl0\\clpadfl3\\clpadr0\\clpadfr3\\clpadb0\\clpadfb3\\clpadt0\\clpadft3\\clcbpat2\\cellx8856\\nestrow}{\\nonesttables\\par}\r\n\\htmlrtf0{\\*\\htmltag0 </Tbody></Table>}{\\*\\htmltag0 </TD>}\\htmlrtf\\pard\\intbl\\cbpat2\\cell\\htmlrtf0{\\*\\htmltag0 </TR>}\\htmlrtf\\pard\r\n\\intbl\\row\r\n\\htmlrtf0{\\*\\htmltag0 <tr><td valign="top" style="background:#2A3B45;padding:0cm 0cm 0cm 0cm">}{\\*\\htmltag0 <table class="MsoNormalTable" border="0" cellspacing="0" cellpadding="0" width="600" style="width:450.0pt;background:#2A3B45">}\\htmlrtf\r\n\\trowd\\irow1\\irowband1\\trcbpat2\\clcbpat8\\clpadl0\\clpadfl3\\clpadr0\\clpadfr3\\clpadb0\\clpadfb3\\clpadt0\\clpadft3\\cellx8856\\htmlrtf0\r\n{\\*\\htmltag0 <tbody>}{\\*\\htmltag0 <tr><td style="padding:0cm 0cm 0cm 0cm">}{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly">}{\\*\\htmltag0 <span style="color:white">}{\\*\\htmltag0 <a href="https://www.sss.com/" target="_blank"><span style="font-size:10.0pt;color:silver;mso-fareast-language:EN-GB;text-decoration:none">}\\pard\r\n\\intbl\\itap2\\cbpat8\\plain{\\*\\htmltag0 <img border="0" width="600" height="84" style="width:6.25in;height:.875in" id="Picture_x0020_4" src="cid:image002.jpg@01D82331.3F8C7950"></Span>}\\htmlrtf\r\n{\\field{\\*\\fldinst HYPERLINK "https://www.sss.com/" }{\\fldrslt\\htmlrtf0{\\*\\htmltag0 }\\htmlrtf\\objattph  \\htmlrtf0{\\*\\htmltag0 </A>}\\htmlrtf\r\n}}\\htmlrtf0{\\*\\htmltag0 </Span><span style="font-size:10.0pt;color:#000001;mso-fareast-language:EN-GB"><o:p></o:p></Span></P>}{\\*\\htmltag0 </TD>}\\htmlrtf\r\n\\nestcell{\\nonesttables\\tab}\\htmlrtf0{\\*\\htmltag0 </TR>}\\htmlrtf\\pard\\intbl\\itap2{\\*\\nesttableprops\\trowd\\irow0\\irowband0\\trcbpat8\r\n\\clpadl0\\clpadfl3\\clpadr0\\clpadfr3\\clpadb0\\clpadfb3\\clpadt0\\clpadft3\\clcbpat8\\cellx8856\\nestrow}{\\nonesttables\\par}\r\n\\htmlrtf0{\\*\\htmltag0 </Tbody></Table>}{\\*\\htmltag0 </TD>}\\htmlrtf\\pard\\intbl\\cbpat8\\cell\\htmlrtf0{\\*\\htmltag0 </TR>}\\htmlrtf\\pard\r\n\\intbl\\row\r\n\\htmlrtf0{\\*\\htmltag0 <tr><td valign="top" style="padding:0cm 0cm 0cm 0cm">}{\\*\\htmltag0 <table class="MsoNormalTable" border="0" cellspacing="0" cellpadding="0">}\\htmlrtf\r\n\\trowd\\irow2\\irowband2\\trcbpat2\\clpadl0\\clpadfl3\\clpadr0\\clpadfr3\\clpadb0\\clpadfb3\\clpadt0\\clpadft3\\clcbpat2\\cellx8856\\htmlrtf0\r\n{\\*\\htmltag0 <tbody>}{\\*\\htmltag0 <tr style="height:12.0pt"><td style="padding:0cm 0cm 0cm 0cm;height:12.0pt">}{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly">}{\\*\\htmltag0 <span style="font-size:10.0pt;color:#000001;mso-fareast-language:EN-GB">}{\\*\\htmltag0 <img border="0" width="1" height="20" style="width:.0138in;height:.2083in" id="Picture_x0020_5" src="cid:image001.gif@01D82331.3F8C7950"></Span>}\\pard\r\n\\intbl\\itap2\\cbpat2\\plain{\\*\\htmltag0 }\\htmlrtf\\objattph  \\htmlrtf0{\\*\\htmltag0 <span style="font-size:10.0pt;color:#000001;mso-fareast-language:EN-GB"><o:p></o:p></Span></P>}{\\*\\htmltag0 </TD>}\\htmlrtf\r\n\\nestcell{\\nonesttables\\tab}\\htmlrtf0{\\*\\htmltag0 </TR>}\\htmlrtf\\pard\\intbl\\itap2{\\*\\nesttableprops\\trowd\\irow0\\irowband0\\trcbpat2\r\n\\trrh240\\clpadl0\\clpadfl3\\clpadr0\\clpadfr3\\clpadb0\\clpadfb3\\clpadt0\\clpadft3\\clcbpat2\\cellx8856\\nestrow}{\\nonesttables\\par}\r\n\\htmlrtf0{\\*\\htmltag0 <tr><td style="padding:0cm 0cm 0cm 0cm">}{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly">}{\\*\\htmltag0 <span style="font-size:7.5pt;font-family:"Verdana",sans-serif;color:#3C3C3B;mso-fareast-language:EN-GB">}\\pard\r\n\\intbl\\itap2\\cbpat2\\plain\\htmlrtf{\\f3\\lang2057\\cf9\\fs15\\htmlrtf0 7b/7c Imperial Studios, Imperial Road, Fulham, London SW6 2AG{\\*\\htmltag0 <br>}\\htmlrtf\r\n}{\\f3\\lang2057\\cf9\\fs15\\line\r\n\\htmlrtf0{\\*\\htmltag0\\par}United Kingdom Company no. 05608752 (England) VAT no. GB 894344685{\\*\\htmltag0 <o:p></o:p></Span>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 </P>}\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly"><span style="font-size:7.5pt;font-family:"Verdana",sans-serif;color:#3C3C3B;mso-fareast-language:EN-GB">}{\\*\\htmltag0 <o:p>}\\pard\r\n\\intbl\\itap2\\cbpat2\\plain\\htmlrtf{\\f3\\lang2057\\cf9\\fs15\\htmlrtf0\\~{\\*\\htmltag0 </o:p></Span>}\\htmlrtf}\\htmlrtf0{\\*\\htmltag0 </P>}\\htmlrtf\r\n\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly"><span style="font-size:7.5pt;font-family:"Verdana",sans-serif;color:#3C3C3B;mso-fareast-language:EN-GB">}{\\*\\htmltag0 <o:p>}\\pard\r\n\\intbl\\itap2\\cbpat2\\plain\\htmlrtf{\\f3\\lang2057\\cf9\\fs15\\htmlrtf0\\~{\\*\\htmltag0 </o:p></Span>}\\htmlrtf}\\htmlrtf0{\\*\\htmltag0 </P>}\\htmlrtf\r\n\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly"><span style="font-size:7.5pt;font-family:"Verdana",sans-serif;color:#3C3C3B;mso-fareast-language:EN-GB">}{\\*\\htmltag0 <o:p>}\\pard\r\n\\intbl\\itap2\\cbpat2\\plain\\htmlrtf{\\f3\\lang2057\\cf9\\fs15\\htmlrtf0\\~{\\*\\htmltag0 </o:p></Span>}\\htmlrtf}\\htmlrtf0{\\*\\htmltag0 </P>}\\htmlrtf\r\n\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly"><span style="font-size:7.5pt;font-family:"Verdana",sans-serif;color:#3C3C3B;mso-fareast-language:EN-GB">}{\\*\\htmltag0 <o:p>}\\pard\r\n\\intbl\\itap2\\cbpat2\\plain\\htmlrtf{\\f3\\lang2057\\cf9\\fs15\\htmlrtf0\\~{\\*\\htmltag0 </o:p></Span>}\\htmlrtf}\\htmlrtf0{\\*\\htmltag0 </P>}\\htmlrtf\r\n\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly"><span style="font-size:7.5pt;font-family:"Verdana",sans-serif;color:#3C3C3B;mso-fareast-language:EN-GB">}{\\*\\htmltag0 <o:p>}\\pard\r\n\\intbl\\itap2\\cbpat2\\plain\\htmlrtf{\\f3\\lang2057\\cf9\\fs15\\htmlrtf0\\~{\\*\\htmltag0 </o:p></Span>}\\htmlrtf}\\htmlrtf0{\\*\\htmltag0 </P>}{\\*\\htmltag0 </TD>}\\htmlrtf\r\n\\nestcell{\\nonesttables\\tab}\\htmlrtf0{\\*\\htmltag0 </TR>}\\htmlrtf\\pard\\intbl\\itap2{\\*\\nesttableprops\\trowd\\irow1\\irowband1\\trcbpat2\r\n\\clpadl0\\clpadfl3\\clpadr0\\clpadfr3\\clpadb0\\clpadfb3\\clpadt0\\clpadft3\\clcbpat2\\cellx8856\\nestrow}{\\nonesttables\\par}\r\n\\htmlrtf0{\\*\\htmltag0 <tr style="height:12.0pt"><td style="padding:0cm 0cm 0cm 0cm;height:12.0pt">}{\\*\\htmltag0 <p class="MsoNormal" style="mso-element:frame;mso-element-frame-hspace:2.25pt;mso-element-wrap:around;mso-element-anchor-vertical:paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly">}{\\*\\htmltag0 <span style="font-size:10.0pt;color:#000001;mso-fareast-language:EN-GB">}{\\*\\htmltag0 <img border="0" width="1" height="20" style="width:.0138in;height:.2083in" id="Picture_x0020_6" src="cid:image001.gif@01D82331.3F8C7950"></Span>}\\pard\r\n\\intbl\\itap2\\cbpat2\\plain{\\*\\htmltag0 }\\htmlrtf\\objattph  \\htmlrtf0{\\*\\htmltag0 <span style="font-size:10.0pt;color:#000001;mso-fareast-language:EN-GB"><o:p></o:p></Span></P>}{\\*\\htmltag0 </TD>}\\htmlrtf\r\n\\nestcell{\\nonesttables\\tab}\\htmlrtf0{\\*\\htmltag0 </TR>}\\htmlrtf\\pard\\intbl\\itap2{\\*\\nesttableprops\\trowd\\irow2\\irowband2\\trcbpat2\r\n\\trrh240\\clpadl0\\clpadfl3\\clpadr0\\clpadfr3\\clpadb0\\clpadfb3\\clpadt0\\clpadft3\\clcbpat2\\cellx8856\\nestrow}{\\nonesttables\\par}\r\n\\htmlrtf0{\\*\\htmltag0 </Tbody></Table>}{\\*\\htmltag0 </TD>}\\htmlrtf\\pard\\intbl\\cbpat2\\cell\\htmlrtf0{\\*\\htmltag0 </TR>}\\htmlrtf\\pard\r\n\\intbl\\row\r\n\\htmlrtf0{\\*\\htmltag0 </Tbody></Table>}{\\*\\htmltag0 <p class="MsoNormal"><span style="mso-fareast-language:EN-GB">}{\\*\\htmltag0 <o:p>}\\pard\r\n\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0\\~{\\*\\htmltag0 </o:p></Span>}\\htmlrtf}\\htmlrtf0{\\*\\htmltag0 </P>}\\htmlrtf\\par\r\n\\htmlrtf0{\\*\\htmltag0 <p class="MsoNormal"><o:p>}\\pard\\plain\\htmlrtf{\\f2\\lang2057\\fs22\\htmlrtf0\\~{\\*\\htmltag0 </o:p></P>}\\htmlrtf\r\n}\\htmlrtf0{\\*\\htmltag0 }{\\*\\htmltag0 </Div>}{\\*\\htmltag0 </Body>}{\\*\\htmltag0 </Html>}}\r\n'
```

**Comment by marcboivin** [comment]
Issue on RFTDE https://github.com/seamustuohy/RTFDE/issues/5

**Comment by TheElementalOfDestruction** [comment]
Unless it has a second "during the handling of this exception" part that mentions extract_msg as the source of the exception, not much that can be done from us. It's not an issue with my code that it doesn't like your RTF. If you are getting another one of those, let me know what section of extract_msg is throwing an error.

**Comment by TheElementalOfDestruction** [comment]
Correction: looking closer at the traceback it looks like it may have fully interfered with the main runner, cutting off any further processing. I'll take a look to make sure that is working correctly

**Comment by TheElementalOfDestruction** [comment]
Okay, the error should no longer prevent opening the file, but if you are saving with the plain text body you will still have issues. Biggest thing this *should* solve is that if you are not trying to save the plain text body then this error should not stop you.

If you could test that with the next-release branch if possible then that would be appreciated.

**Comment by TheElementalOfDestruction** [comment]
If you can just test it yourself and make sure the traceback doesn't point to the open function then I have done my job successfully. The error is from another module and I don't understand it enough to handle it any other way than just throwing it if it matters, and not throwing it if it doesn't matter for the situation.

Additionally, saving that file using RTF body should work with no exceptions. If you get an exception still just let me know the traceback and errors without sensitive information and that will be fine too.

**Comment by TheElementalOfDestruction** [comment]
The more I try to look into the details of what is happening the stranger this gets. The part it says has an error doesn't exist which makes me think significant changes are being made to the text before it gets processed by the part that is having an issue, significant changes that may actually be contributing to the issue. I've started diving into the way the RTFDE module actually works to figure this out.

**Comment by TheElementalOfDestruction** [comment]
I released the new version which should make it so at least opening an MSG file is safe to do, but trying to access the body might still create an exception when it is being generated. Let me know if that still has issues (you will still be unable to save the message in plain text, and will probably have an issue if you try to save in HTML if the body has no HTML stream, as the same code will be used to try and generate it. As the RTFDE module isn't properly working for it, there isn't anything I can do except try to use a custom grammar with it but I'd have to, you know, figure out how to make that work properly 😅)

**Comment by marcboivin** [comment]
Thank you sir. I fell your pain. Tried to figure out how grammars work and gave up on it. 

I'm testing it right now.

**Comment by marcboivin** [comment]
So, everything works but for getting the body. Until we get feedback from the RTFDE guy I think it's the best that's reasonable to do. 

Thanks
